name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        pip list
        
    - name: Create empty data files
      run: |
        echo "{}" > property_notes.json
        echo "{}" > saved_properties.json
        python -c "import pickle; f=open('api_cache.pkl','wb'); pickle.dump({},f); f.close()"
      
    - name: Build executable
      run: python build.py
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: 부동산매물분석
        path: |
          dist/부동산매물분석.exe
          songdo_apartments_listings.csv 